### ISSUE TITLE
Plain document license doesn't work

### ISSUE THREAD

**Issue by rigow** [w3c/licenses#2]
By contributors licensing under document license, W3C does not acquire sufficient rights. You have only thought distribution and not acquisition. W3C needs both.

**Comment by wseltzer** [comment]
@rigow Can you explain further? Contribution to a joint work under the W3C document license gives W3C full rights to modify and redistribute, which is what we need to create specs. I'm not aware that W3C has ever asked for an assignment of rights.

**Comment by rigow** [comment]
I may be able to answer if we detail who contributes what to which work and who gives a license with what content to whom. Because in your actual wording W3C just acquires the right to publish something under the document license. Tell me where the document license gives W3C rights to modify and distribute and repurpose. And no, it is not about assignment of rights (which doesn't work for droit d'auteur anyway) Note that W3C is not necessarily a contributor to the joint work in all cases

**Comment by wseltzer** [comment]
All we want to do is modify and publish under the document license, both of which anyone else licensing under the document license -- having signed a Member Agreement or IE Agreement -- gives us the right to do.

**Comment by wseltzer** [comment]
Closing this issue, as the plan is to document current state, to make github participation match other forms of input.
