### ISSUE TITLE
Suggestions: specify how to ID contributors

### ISSUE THREAD

**Issue by wseltzer** [w3c/licenses#3]
[suggestions from Wayne Carr] 
In the part in CONTRIBUTING.md about specifying the contributors, it would be good to specify how to do that.  In the charter on the Community Group site, it says: "In the commit, if practical, this information should be in the form {Contributors: ["@githubusername1","@githubusername2"]}."  The particular format Robin should provide.  The one we use is a very simple JSON object.  Tools could pick up incorrectly formatted text by flagging comments with usernames that aren't in the right form for manual processing.  So, "@hendrix hates this idea." doesn't automatically make hendrix a contributor to it :)

The reason to specify it is that you need to know something about the format to be able to create tools that automate determining who the contributors are.  (In the W3C account information, users could provide their GitHub username so we can tell where they make GitHub contributions).

**Comment by darobin** [comment]
I don't think that pasting JSON is a viable approach, it's just too much work, people will get it wrong, etc. But equally, just mentioning someone in a discussion thread shouldn't make that person a willing contributor.

My thinking was in between the two. Having "+@wseltzer" on a line of its own adds you as a contributor to any open pull request. This allows people to also do "-@darobin" if someone was added by mistake.

**Comment by wseltzer** [comment]
Added: 

In the commit, please include on a new line,
Contributors: +@githubusername1, +@githubusername2, ...

**Comment by wseltzer** [comment]
Updated to Robin's more detailed explanation.
