### ISSUE TITLE
[CG CONTRIBUTING.md] point to LICENSE.md for terms under which contributions are made.

### ISSUE THREAD

**Issue by wcarr** [w3c/licenses#5]
In the Web-NFC CG CONTRIBUTING.MD file it says as the second sentence:

"All contributions are made under the terms described in the LICENSE.md file.".

As it is that just talks about the CLA which doesn't apply at all to non-specification reports.  Better to also point to the LICENSE file so they know all their contributions will be licensed as that LICENSE file indicates.

**Comment by wseltzer** [comment]
It now mentions both CLA and Software License.
